core/urls.py
from django.urls import path
from core import views
from rest_framework.routers import DefaultRouter

app_name = "core"

router = DefaultRouter()

urlpatterns = [
    path("", views.index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),
    path("create_post/", views.create_post, name="create_post"),
    path("like_post/", views.like_post, name="like_post"),
    path("comment_post/", views.comment_on_post, name="comment_post"),
    path("like_comment/", views.like_comment, name="like_comment"),
    path("reply_comment/", views.reply_comment, name="reply_comment"),
    path("delete_comment/", views.delete_comment, name="delete_comment"),
    path("add_friend/", views.add_friend, name="add_friend"),
    path("accept_friend_request/", views.accept_friend_request, name="accept_friend_request"),
    path("reject_friend_request/", views.reject_friend_request, name="reject_friend_request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),
    path("block_user/", views.block_user, name="block_user")
]

facebook_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.routing import websocket_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ws", include(websocket_urlpatterns))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from userauths import views

app_name = "userauths"

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("my-profile/", views.my_profile, name="my-profile"),
    path("profile/<username>", views.friend_profile, name="profile")
]

userauths/models.py
import shortuuid
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify
from shortuuid.django_fields import ShortUUIDField

GENDER = (
    ("male", "Male"),
    ("female", "Female"),
    ("other", "Other")
)


RELATIONSHIP = (
    ("single", "Single"),
    ("married", "Married"),
    ("relationship", "In a relationship"),
    ("open_relation", "Open Relation")
)


def user_directory_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (instance.user.id, ext)
    return 'user_{0}/{1}'.format(instance.user.id, filename)


class User(AbstractUser):
    full_name = models.CharField(max_length=200)
    username = models.CharField(max_length=200)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=200)
    gender = models.CharField(max_length=100, choices=GENDER)
    otp = models.CharField(max_length=10, null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to=user_directory_path, null=True, blank=True, default="cover.jpg")
    image = models.ImageField(upload_to=user_directory_path, null=True, blank=True, default="default.jpg")
    full_name = models.CharField(max_length=200, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, default="other")
    relationship = models.CharField(max_length=100, choices=RELATIONSHIP, default="single")
    about_me = models.CharField(max_length=700, null=True, blank=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    working_at = models.CharField(max_length=200, null=True, blank=True)
    instagram = models.CharField(max_length=200, null=True, blank=True)
    whatsapp = models.CharField(max_length=200, null=True, blank=True)
    verified = models.BooleanField(default=False)
    followers = models.ManyToManyField(User, blank=True, related_name="followers")
    following = models.ManyToManyField(User, blank=True, related_name="following")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    blocked = models.ManyToManyField(User, blank=True, related_name="blocked")
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.slug == "" or self.slug is None:
            uuid_key = shortuuid.uuid()
            uniqueid = uuid_key[:2]
            self.slug = slugify(self.full_name) + '-' + str(uniqueid.lower())
        super(Profile, self).save(*args, **kwargs)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from userauths.models import User


class UserRegistrationForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Full Name"}), max_length=100, required=True)
    username = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Username"}), max_length=100, required=True)
    phone = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Phone"}), max_length=100, required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Email"}), max_length=100, required=True)
    password1 = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Password"}), max_length=100, required=True)
    password2 = forms.CharField(widget=forms.TextInput(attrs={'id': "", 'placeholder': "Confirm Password"}), max_length=100, required=True)

    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'phone', 'gender', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = "with-border"

userauths/views.py
import json

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect

from core.models import Post, FriendRequest
from userauths.forms import UserRegistrationForm
from userauths.models import Profile, User


def register_view(request):
    if request.user.is_authenticated:
        return JsonResponse({'error': "You are already registered!"}, status=400)

    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data.get("full_name")
        phone = form.cleaned_data.get("phone")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")

        user = authenticate(email=email, password=password)
        login(request, user)

        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.save()
        return JsonResponse({'message': f"Hi {full_name}. Your account was created successfully."}, status=201)

    return JsonResponse({'error': form.errors}, status=400)


def login_view(request):
    if request.user.is_authenticated:
        return JsonResponse({'error': "You are already logged in!"}, status=400)
    if request.method == "POST":
        name = request.POST.get("email")
        password = request.POST.get("password")
        try:
            if '@' in name:
                user = authenticate(email=name, password=password)
            else:
                login_user = User.objects.filter(username=name)
                if len(login_user) > 0:
                    user = authenticate(username=login_user[0].email, password=password)
                else:
                    return JsonResponse({'error': "Wrong username or password"}, status=400)
            if user is not None:
                login(request, user)
                return JsonResponse({'message': "Login successful"}, status=200)
            else:
                return JsonResponse({'error': "Wrong username or password"}, status=400)
        except Exception as ex:
            print(ex)
            return JsonResponse({'error': "Something went wrong. Please try again."}, status=500)

    return JsonResponse({'error': "Invalid request method"}, status=405)


def logout_view(request):
    logout(request)
    messages.success(request, "you are logged out")
    if not request.user.is_authenticated:
        return redirect("userauths:sign-up")


@login_required
def my_profile(request):
    profile = request.user.profile
    posts = Post.objects.filter(active=True, user=request.user).order_by("-id")
    context = {
        "profile": profile,
        "posts": posts
    }
    return render(request, "userauths/my-profile.html", context)


@login_required
def friend_profile(request, username):
    profile = Profile.objects.get(user__username=username)
    if request.user.profile == profile:
        return redirect("userauths:my-profile")

    posts = Post.objects.filter(active=True, user=profile.user).order_by("-id")
    _bool = False
    bool_friend = False
    sender = request.user
    receiver = profile.user

    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        if friend_request:
            _bool = True
        else:
            _bool = False
    except:
        _bool = False

    context = {
        "profile": profile,
        "posts": posts,
        "bool": _bool,
        "posts": posts
    }
    return render(request, "userauths/friend-profile.html", context)

templates/userauths/sign-up.html
    {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="assets/images/favicon.png" rel="icon" type="image/png">

    <!-- Basic Page Needs
        ================================================== -->
    <title>Socialite Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Socialite is - Professional A unique and beautiful collection of UI elements">

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">

    <!-- CSS 
    ================================================== -->
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <style>
        body {
            background-color: #f0f2f5;
        }
    </style>

</head>

<body>


    <div class="lg:flex max-w-5xl min-h-screen mx-auto p-6 py-10">
        <div class="flex flex-col items-center lg: lg:flex-row lg:space-x-10">

            <div class="lg:mb-12 flex-1 lg:text-left text-center">
                <img src="{% static 'assets/images/logo.png' %}" alt="" class="lg:mx-0 lg:w-52 mx-auto w-40">
                <p class="font-medium lg:mx-0 md:text-2xl mt-6 mx-auto sm:w-3/4 text-xl"> Connect with friends and the world around you on Socialite.</p>
            </div>
            <div class="lg:mt-0 lg:w-96 md:w-1/2 sm:w-2/3 mt-10 w-full">
                {% if form.errors %}
                    <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                        {{form.errors}}
                    </div>
                {% endif %}
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == "error" %}
                            <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                                {{message}}
                            </div>
                        {% endif %}
                        {% if message.tags == "success" %}
                            <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                                {{message}}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <form class="p-6 space-y-4 relative bg-white shadow-lg rounded-lg" method="POST" action="{% url 'userauths:sign-in' %}">
                    {% csrf_token %}
                    <input type="text" name="email" placeholder="Email or username" class="with-border">
                    <input type="password" name="password" placeholder="Password" class="with-border">
                    <button type="submit" class="bg-blue-600 font-semibold p-3 rounded-md text-center text-white w-full">
                        Log In
                    </button>
                    <a href="#" class="text-blue-500 text-center block"> Forgot Password? </a>
                    <hr class="pb-3.5">
                    <div class="flex">
                        <a href="#register" type="button" class="bg-green-600 hover:bg-green-500 hover:text-white font-semibold py-3 px-5 rounded-md text-center text-white mx-auto" uk-toggle>
                            Create New Account
                        </a>
                    </div>
                </form>

                <div class="mt-8 text-center text-sm"> <a href="#" class="font-semibold hover:underline"> Create a Page </a> for a celebrity, band or business </div>
            </div>

        </div>
    </div>

    <!-- This is the modal -->
    <div id="register" uk-modal>
        <div class="uk-modal-dialog uk-modal-body rounded-xl shadow-2xl p-0 lg:w-5/12">
            <button class="uk-modal-close-default p-3 bg-gray-100 rounded-full m-3" type="button" uk-close></button>
            <div class="border-b px-7 py-5">
                <div class="lg:text-2xl text-xl font-semibold mb-1"> Sign Up</div>
                <div class="text-base text-gray-600"> It’s quick and easy.</div>
            </div>
            {% if form.errors %}
                <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                    {{form.errors}}
                </div>
            {% endif %}
            <form class="p-7 space-y-5" method="POST">
                {% csrf_token %}
                <div class="grid lg:grid-cols-2 gap-5">
                    {{form.full_name}}
                    {{form.username}}
                </div>
                {{form.email}}
                {{form.password1}}
                {{form.password2}}

                <div class="grid lg:grid-cols-2 gap-3">
                    <div>
                        <label class="mb-0"> Gender </label>
                        {{form.gender}}
                    </div>
                    <div>
                        <label class="mb-2"> Phone: optional  </label>
                        {{form.phone}}
                    </div>
                </div>
                <p class="text-xs text-gray-400 pt-3">By clicking Sign Up, you agree to our
                    <a href="#" class="text-blue-500">Terms</a>,
                    <a href="#">Data Policy</a> and
                    <a href="#">Cookies Policy</a>. You may receive SMS Notifications from us and can opt out any time.
                </p>
                <div class="flex">
                    <button type="submit" class="bg-blue-600 font-semibold mx-auto px-10 py-3 rounded-md text-center text-white">
                        Get Started
                    </button>
                </div>
            </form>

        </div>
    </div>

    <!-- For Night mode -->
    <script>
        (function(window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);

        (function(window, document, undefined) {

            'use strict';

            // Feature test
            if (!('localStorage' in window)) return;

            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;

            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function(event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);

        })(window, document);
    </script>

    <!-- Javascript
    ================================================== -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap-select.min.js' %}"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

</body>

</html>