core/urls.py
from django.urls import path
from core import views
from rest_framework.routers import DefaultRouter

app_name = "core"

router = DefaultRouter()

urlpatterns = [
    path("", views.index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),
    path("create_post/", views.create_post, name="create_post"),
    path("like_post/", views.like_post, name="like_post"),
    path("comment_post/", views.comment_on_post, name="comment_post"),
    path("like_comment/", views.like_comment, name="like_comment"),
    path("reply_comment/", views.reply_comment, name="reply_comment"),
    path("delete_comment/", views.delete_comment, name="delete_comment"),
    path("add_friend/", views.add_friend, name="add_friend"),
    path("accept_friend_request/", views.accept_friend_request, name="accept_friend_request"),
    path("reject_friend_request/", views.reject_friend_request, name="reject_friend_request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),
    path("block_user/", views.block_user, name="block_user")
]

facebook_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.routing import websocket_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("ws", include(websocket_urlpatterns))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/chat/inbox_detail.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

        <!-- Main Contents -->
    <div class="main_content">

        <span uk-toggle="target: .message-content;" class="fixed left-0 top-36 bg-red-600 z-10 py-1 px-4 rounded-r-3xl text-white"> Users</span>

        <div class="messages-container">
            <div class="messages-container-inner">


                <div class="messages-inbox">
                    <div class="messages-headline">
                        <div class="input-with-icon" hidden>
                            <input id="autocomplete-input" type="text" placeholder="Search">
                            <i class="icon-material-outline-search"></i>
                        </div>
                        <h2 class="text-2xl font-semibold">Chats</h2>
                        <span class="absolute icon-feather-edit mr-4 text-xl uk-position-center-right cursor-pointer"></span>
                    </div>
                    <div class="messages-inbox-inner" data-simplebar>
                        <ul>
                            {% for m in message_list %}
                                {% if request.user == m.sender %}
                                    <li>
                                        <a href="{% url 'core:inbox_detail' m.receiver.username %}">
                                            <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{ m.receiver.profile.image.url }}" alt=""></div>

                                            <div class="message-by">
                                                <div class="message-by-headline">
                                                    <h5>{{ m.receiver.profile.full_name }}</h5>
                                                    <span style="font-size: 13px;">{{ m.date|timesince }}</span>
                                                </div>
                                                <p>{{ m.message }}</p>
                                            </div>
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user == m.receiver %}
                                	<li>
                                        <a href="{% url 'core:inbox_detail' m.sender.username %}">
                                            <div class="message-avatar"><i class="status-icon status-online"></i><img src="{{ m.sender.profile.image.url }}" alt=""></div>

                                            <div class="message-by">
                                                <div class="message-by-headline">
                                                    <h5>{{ m.sender.profile.full_name }}</h5>
                                                    <span style="font-size: 13px;">{{ m.date|timesince }}</span>
                                                </div>
                                                <p>{{ m.message }}</p>
                                            </div>
                                        </a>
                                    </li>
                                {% endif %}
                                {% empty %}
                                <li>
                                    <a href="#">
                                        <div class="message-by">
                                            <div class="message-by-headline">
                                                <h5>No messages yet</h5>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>


                <div class="message-content">

                    <div class="messages-headline">
                        <div class="flex">
                            <img class="mr-1" src="{{ receiver_details.profile.image.url }}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="">
                            <h4 class="ml-1"> {{ receiver_details.profile.full_name|title }} </h4>
                        </div>
                        <a href="#" id="block-user-btn" data-block-user="{{receiver_details.id}}" class="message-action text-red-500 block-text{{receiver_details.id}}"><i class="icon-feather-trash-2"></i> <span class="md:inline hidden"> Block {{receiver_details.profile.full_name|title}}</span> </a>
                    </div>

                    <div class="message-content-scrolbar" data-simplebar>

                        <!-- Message Content Inner -->
                        <div class="message-content-inner chat_container">

                            {% for m in message_detail %}
                                {% if m.sender == request.user %}
                                    <div class="message-bubble me">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{ m.message }}</p>
                                                <!-- <p style="font-size: 12px; color: rgb(255, 255, 255, 0.557)">{{ m.date|timesince }} ago</p> -->
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% else %}
                                    <div class="message-bubble">
                                        <div class="message-bubble-inner">
                                            <div class="message-avatar"><img src="{{ m.sender.profile.image.url }}" alt=""></div>
                                            <div class="message-text">
                                                <p>{{ m.message }}</p>
                                                <!-- <p style="font-size: 12px; color: rgb(149, 149, 149)">{{ m.date|timesince }} ago</p> -->
                                            </div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                {% endif %}
                            {% endfor %}

                            <div id="chat-messages"></div>

                        </div>
                        <!-- Message Content Inner / End -->

                        <!-- Reply Area -->
                        <div class="message-reply">
                            <textarea id="chat-input" cols="1" rows="1" placeholder="Your Message"></textarea>
                            <button id="send-btn" class="button ripple-effect">Send</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script>
        var receiver = null
        var receiver_id = "{{receiver.username}}"
        var logged_in = "{{request.user.username}}"
        const pathname = window.location.pathname;
        const parts = pathname.split("/");
        const username = parts[parts.length - 2]
        console.log(username);

        if (receiver_id === logged_in) {
            receiver = receiver_id
        } else {
            receiver = receiver_id
        }

        var socket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + receiver + '/');

        socket.onopen = function(){
            console.log("Websocket Connection Established");
        }
        
        socket.onmessage = function(event){
            var data = JSON.parse(event.data);
            var message = data.message;
            var sender = data.sender;
            var profile_image = data.profile_image;
            var receiver = data.receiver;

            if (sender === "{{sender}}") {
                var chatMessage = '<div class="message-bubble me">';
                chatMessage += '<div class="message-bubble-inner">'
                chatMessage += '<div class="message-avatar"><img src="' + profile_image + '" alt=""></div>'
                chatMessage += '<div class="message-text">'
                chatMessage += '<p>' + message + '</p>'
                chatMessage += '<p style="font-size: 12px; color: rgb(255, 255, 255, 0.557)">{{ m.date|timesince }} ago</p>'
                chatMessage += '</div>'
                chatMessage += '</div>'
                chatMessage += '<div class="clearfix"></div>'
                chatMessage += '</div>'

                $("#chat-messages").append(chatMessage)
            } else {
                var chatMessage = '<div class="message-bubble">';
                chatMessage += '<div class="message-bubble-inner">'
                chatMessage += '<div class="message-avatar"><img src="' + profile_image + '" alt=""></div>'
                chatMessage += '<div class="message-text">'
                chatMessage += '<p>' + message + '</p>'
                chatMessage += '<p style="font-size: 12px; color: rgb(255, 255, 255, 0.557)">{{ m.date|timesince }} ago</p>'
                chatMessage += '</div>'
                chatMessage += '</div>'
                chatMessage += '<div class="clearfix"></div>'
                chatMessage += '</div>'

                $("#chat-messages").append(chatMessage)
                var chatContainer = document.querySelector(".chat_container")
                chatContainer.scrollTop = chatContainer.scrollHeight
            }
        }

        socket.onclose = function(){
            console.log("Websocket Connection Closed");
        }

        $("#send-btn").on("click", function(){
            var input = $("#chat-input")
            var message = input.val()
            var sender = "{{request.user.username}}"
            var data = {
                'message': message,
                'sender': sender,
                'receiver': username
            };
            socket.send(JSON.stringify(data))
            input.val("")
        })

        $(document).ready(function(){
            $(".chat_container").scrollTop(100000000)
        })

    </script>

{% endblock %}